### ISSUE TITLE
version mismatch with PyPi

### ISSUE THREAD

**Issue by fstrazzante** [Attol8/istatapi#18]
Thank you for the package! It's very useful!
It works good, but I got the same time period error of this issue: https://github.com/Attol8/istatapi/issues/16
Looks like the error is fixed with this merge: https://github.com/Attol8/istatapi/commit/e4c8d9f469ca54126004dd2b3d58c96da43dc4a1
But probably is because PyPI is out of sync, because I download the files from PyPI and I can't see the edit on the file istatapi/retrieval.py .
I fix it manually replacing the istatapi/retrieval.py file with the one of the commit: https://github.com/Attol8/istatapi/commit/e4c8d9f469ca54126004dd2b3d58c96da43dc4a1

**Comment by Attol8** [comment]
hey @fstrazzante sorry for being late on this, I was really busy with work lately! I am glad you liked the package, hopefully you can use it successfully in your own personal projects. 

Thanks for opening the issue. I should have fixed in the latest release 0.0.7. As you said the pypi files were not up to date with the latest version of the package.
